config/routes.rb
Rails.application.routes.draw do
  get 'index', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :show
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update', as: :update_task
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    find_task
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path
  end

  def edit
    find_task
  end

  def update
    find_task
    updated_task = task_params
    updated_task[:completed] = params[:task][:completed] == 'true'
    @task.update(updated_task)
    redirect_to show_path(@task)
  end

  def destroy
    find_task
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/81957c30be.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="card p-3">
    <h2 class="">EDIT TASK</h2>
    <%= simple_form_for @task, url: update_task_path(@task) do |f| %>
      <%= f.input :title %>
      <%= f.input :details %>
      <%= f.input :completed, as: :boolean, checked_value: true, unchecked_value: false %>
      <div class="d-flex justify-content-between">
        <%= f.button :submit, class: "btn-primary" %>
        <%= link_to "Cancel", show_path(@task), class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class='text-center'>Tasks</h1>
  <div class="text-end">
    <%= link_to new_task_path do %>
      <i class="far fa-plus-square fs-1 mb-2 text-muted"></i>
    <% end %>
  </div>
  <ul class="list-group">
    <% @tasks.each do |task| %>
      <%= link_to show_path(task) do %>
        <% if task.completed %>
          <li class="d-inline-flex list-group-item list-group-item-action list-group-item-dark card-subtitle text-decoration-line-through">
        <% else %>
          <li class="d-inline-flex list-group-item list-group-item-action card-subtitle">
        <% end %>
        <%= task.title %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="card p-3">
    <h2 class="">CREATE NEW TASK</h2>
    <%= simple_form_for @task, url: tasks_path do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <div class="d-flex justify-content-between">
      <div>
        <%= f.button :submit, class: "btn-primary" %>
        <%= f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" %>
      </div>
      <%= link_to "Return to tasks list", index_path, class: "btn btn-outline-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="card" style="width: 18rem">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h2 class="card-title"><%= @task.title %></h2>
        <div>
          <%= link_to edit_task_path(@task) do %>
            <i class="far fa-edit me-2"></i>
          <% end %>
          <%= link_to destroy_task_path(@task), method: :delete, data: { confirm: "Are you sure you wish to delete #{@task.title}?" } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
      <h6 class="card-subtitle text-muted fst-italic pt-2 pb-3">
        <%if !@task.completed%>
        Not
        <% end %>
        Completed</h6>
      <p class="card-text"><%= @task.details %></p>
    </div>
  </div>
  <%= link_to "Return to tasks list", index_path, class: "btn btn-outline-primary mt-3" %>
</div>